### ISSUE TITLE
Can't be used to upload build artifacts

### ISSUE THREAD

**Issue by cdaguerre** [drone-plugins/drone-s3#17]
I guess it's because this is a `publish` plugin, but it's not executed when a build fails, thus it can't be used to upload build artifacts for debugging...
Is there an easy way to make it `publish` to s3 even when the build fails?

**Comment by bradrydzewski** [comment]
this is handled at the drone level and not the plugin level, and is already addressed in the upcoming 0.5 release so we can close :)
