### ISSUE TITLE
 image 1.4 on docker hub does not work

### ISSUE THREAD

**Issue by rhafer** [drone-plugins/drone-s3#171]
The `1.4` and the `latest` images published on docker hub do no longer work:

```
docker run docker.io/plugins/s3
{"msg":"exec container process (missing dynamic library?) `/bin/drone-s3`: No such file or directory","level":"error","time":"2024-09-24T08:12:25.600884Z"}
```

**Comment by aslmvc** [comment]
I can also confirm this;

```
latest: Pulling from plugins/s3
Digest: sha256:091cd4d57680ba3a08991434dc2f8edb7b893fea5934fe7b7e2f4acfbaceb6e1
Status: Image is up to date for plugins/s3:latest
standard_init_linux.go:228: exec user process caused: no such file or directory
```

Temporary fix would be to use specific version, e.g. `plugins/s3:1.4.0`

**Comment by hkraal** [comment]
Been hit by this as well, as the impact is potentially large I think it's warrented a ping @Ompragash @vistaarjuneja @dgarg-harness @HenAmar

**Comment by Ompragash** [comment]
@rhafer @aslmvc @hkraal Thank you for reporting the issue, and we apologize for the inconvenience caused. We have re-triggered the build. Please try again in 20 minutes, and it should work.

**Comment by hkraal** [comment]
Can confirm the image is working properly again, thank you all for maintaining it! ❤️

**Comment by rhafer** [comment]
@Ompragash thanks for addressing this so quick.

So I guess this can be closed now.
