### ISSUE TITLE
Unable to use drone secret for aws key and token.

### ISSUE THREAD

**Issue by s3than** [drone-plugins/drone-s3#30]
Using secrets returns the following error, using secrets for other plugins is fine.

InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records. status code: 403, request id: EFA7165BFF6E8129

**Comment by tboerger** [comment]
The error message comes from s3, you seem to define a wrong access key.

**Comment by s3than** [comment]
Hi @tboerger It was because I did the following

`pipeline:
  s3:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "my-bucket-name"
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: public/**/*
    strip_prefix: public/
    target: /target/location
    encryption: AES256
    exclude:
      - **/*.xml`

However removing and using the secrets as ENV works fine
