### ISSUE TITLE
Feature request s3 download mode

### ISSUE THREAD

**Issue by yellowmegaman** [drone-plugins/drone-s3#39]
I'd like to be able to use s3 plugin in reverse, to download artifact.

Golden rule of continuous delivery states that code should only be built once, then deployed without rebuilding.
I was looking at example here: http://docs.drone.io/promoting-builds/
And it seemed to me that it can be improved. 
- build & test & publish artifact w/o deployment event
- get artifact & deploy w/ deployment event

Please let me know whenever idea is worth it.

Thanks a lot in advance!

**Comment by tboerger** [comment]
I don't think that this plugin will get another functionality. The drone plugins are focused on single responsibility, this feature would break that more or less. The plugins should do a simple task, and this task should be done really well. This is currently the case.

**Comment by yellowmegaman** [comment]
Well, understood. Gonna use commands then. Thanks!
