### ISSUE TITLE
Using wildcards doesn't work.

### ISSUE THREAD

**Issue by johnrengelman** [drone-plugins/drone-s3#4]
Code comments indicate that using a `*` will work, but this isn't true. The underlying AWS command requires the use of the `--include` and `--exclude` flags to configure wildcard behavior just like the `s3_sync` plugin.

**Comment by DCRichards** [comment]
Second this, archiving android APKs and would love to be able to do:

`source: /apk/*-release.apk` to specify only these files for example, rather than all in a folder.

**Comment by bradrydzewski** [comment]
replaced the 0.5 version of the plugin with fully-compliant posix globbing
