### ISSUE TITLE
Support setting ContentType and ContentEncoding

### ISSUE THREAD

**Issue by fernandrone** [drone-plugins/drone-s3#54]
Hey,

Currently this plugin does not support setting ContentType and ContentEnconding. At QuintoAndar we use this plugin to upload files to S3 which are then served to different web pages so this is necessary (and should be a pretty common use-case), and is one of the reasons I keep a fork here: https://github.com/quintoandar/drone-s3.

[Drone S3 Sync](http://plugins.drone.io/drone-plugins/drone-s3-sync/) currently supports them.

I have a [Pull Request on the way](https://github.com/drone-plugins/drone-s3/compare/master...quintoandar:add-content-encoding) but would like to consider a few points first.

1. drone-s3-sync uses glob matching, but in my original fork I went for a regex matcher. This allows us to set metadata like this:

```
    content_type:
      ".*(css|cgz)$": "text/css"
      ".*(ttf|woff|woff2)$": "application/octet-stream"
```

I'm fine either way but would like to know if there's more interest in using regex over glob.

2. Have you ever considered merging drone-s3 and drone-s3-sync plugins? A lot of the code is pretty similar, so this means half the maintenance costs. The sync could be a parameter `sync: true` that is false by default.

**Comment by fbcbarbosa** [comment]
Worth noting, there was a PR here from a coworker (https://github.com/drone-plugins/drone-s3/pull/34) that added content_type support which @tboerger reviewed but never got merged.

**Comment by tboerger** [comment]
I have taken more or less the code of the plugin fork within https://github.com/drone-plugins/drone-s3/pull/63 to get this finally integrated.
