### ISSUE TITLE
Support custom endpoint urls

### ISSUE THREAD

**Issue by alexex** [drone-plugins/drone-s3#9]
awscli supports the `--endpoint-url` option which let's a user specify a custom endpoint. If we add the URL to this plugin, users could use this plugin to deploy assets to any S3 compatibles API, [i.e. riak, swiftstack, ceph, skylable, minio](https://www.quora.com/Is-there-open-source-software-that-implements-Amazon-S3-plug-compatible-storage) or similar projects. As it would only be one more optional config option, I think the actual work should be limited.

I'd try it myself but I have never done anything in go and will probably break something.

**Comment by csachs** [comment]
I've quickly hacked together something for this, see pr #14

**Comment by bradrydzewski** [comment]
thanks, these changes were included in the 0.5 upgrade. We ended up switching to use the native Go code instead of the command line utility which is why the PR wasn't merged, but still appreciated!
